# Generated by Django 5.1.4 on 2025-10-17 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0478_facility_discount_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('account_id', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facility.facility', to_field='external_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
